---
- name: Install and configure apache
  hosts: managed
  become: true
  tasks:
    - name: Install apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'
        owner: root
        group: root

    - name: Open http service in firewalld
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
