---
- name: Update the index.html of our basic website
  hosts: eda
  become: true
  tasks:
#    - name: testing webhook
#      debug:
#        msg: webhook successful!
    - name: Update our index.html content
      ansible.builtin.copy:
        src: /home/bkrumme/ansibleprojects/eda_demo/files/index.html
        dest: /var/www/html/
        mode: 0644
