---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000

  rules:
    - name: Push event to repository
      condition: event.payload.repository.sender.login == "bpkrumme"
      action:
        run_playbook:
          name: update_site_code.yml
