---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Listen for a webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Push event to repository
      condition: event.payload.repository.name == "eda_demo"
      action:
        run_playbook:
          name: deploy_site.yml
