all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
    managed:
      hosts:
        node01:
          ansible_host: 192.168.124.98
          apache_listen_port: 80
          cockpit_packages: default
          crypto_policies_policy: DEFAULT:NO-SHA1
          selinux_policy: targeted
          selinux_state: enforcing
          timesync_ntp_servers: &id001
          - hostname: 0.rhel.pool.ntp.org
            iburst: true
          - hostname: 1.rhel.pool.ntp.org
            iburst: true
          - hostname: 2.rhel.pool.ntp.org
            iburst: true
          - hostname: 3.rhel.pool.ntp.org
            iburst: true
          tlog_scope_sssd: all
        node02:
          ansible_host: 192.168.124.232
          apache_listen_port: 80
          cockpit_packages: default
          crypto_policies_policy: DEFAULT:NO-SHA1
          selinux_policy: targeted
          selinux_state: enforcing
          timesync_ntp_servers: *id001
          tlog_scope_sssd: all
        node03:
          ansible_host: 192.168.124.82
          apache_listen_port: 8080
          cockpit_packages: default
          crypto_policies_policy: DEFAULT:NO-SHA1
          selinux_policy: targeted
          selinux_state: permissive
          timesync_ntp_servers:
          - hostname: 0.pool.ntp.org
            iburst: true
          - hostname: 1.pool.ntp.org
            iburst: true
          - hostname: 2.pool.ntp.org
            iburst: true
          - hostname: 3.pool.ntp.org
            iburst: true
          tlog_scope_sssd: all
    ungrouped: {}
