all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
    managed:
      hosts:
        node01:
          ansible_host: 192.168.124.98
        node02:
          ansible_host: 192.168.124.232
        node03:
          ansible_host: 192.168.124.82
    ungrouped: {}
